name: opentelemetry-vector-e2e
services:
  otel-collector-source:
    image: otel/opentelemetry-collector-contrib:${CONFIG_COLLECTOR_VERSION:-latest}
    init: true
    volumes:
      - type: bind
        source: ../../../tests/data/e2e/opentelemetry/logs/collector-source.yaml
        target: /etc/otelcol-contrib/config.yaml
        read_only: true
    ports:
      - "${OTEL_COLLECTOR_SOURCE_GRPC_PORT:-4317}:4317"
      - "${OTEL_COLLECTOR_SOURCE_HTTP_PORT:-4318}:4318"
    command: [ "--config=/etc/otelcol-contrib/config.yaml" ]

  logs-generator:
    image: python:3.11-alpine
    build:
      context: ./generator
    init: true
    depends_on:
      - otel-collector-source
    volumes:
      - type: bind
        source: ./generator
        target: /generator
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "python", "/generator/logs_generator.py", "-n", "100" ]

  otel-collector-sink:
    image: otel/opentelemetry-collector-contrib:${CONFIG_COLLECTOR_VERSION:-latest}
    init: true
    volumes:
      - type: bind
        source: ../../../tests/data/e2e/opentelemetry/logs/collector-sink.yaml
        target: /etc/otelcol-contrib/config.yaml
        read_only: true
      - ../../../tests/data/e2e/opentelemetry/logs/output:/tmp
    ports:
      - "${OTEL_COLLECTOR_SINK_HTTP_PORT:-5318}:5318"

  vector:
    build:
      context: ../../../
      dockerfile: ./scripts/e2e/Dockerfile
      args:
        FEATURES: e2e-tests-opentelemetry
        RUST_VERSION: ${RUST_VERSION:-1.88}
    init: true
    depends_on:
      - otel-collector-source
      - otel-collector-sink
    volumes:
      - type: bind
        source: ../../../tests/data/e2e/opentelemetry/logs/vector.yaml
        target: /etc/vector/vector.yaml
        read_only: true
      - ../../../tests/data/e2e/opentelemetry/logs/output:/tmp
    environment:
      - VECTOR_LOG=${VECTOR_LOG:-info}
      - FEATURES=e2e-tests-opentelemetry
    command: [ "vector", "-c", "/etc/vector/vector.yaml" ]

volumes:
  # The containers write output logs in this volume
  otel_logs:
