name: Release Suite

on:
  push:
    tags:
      - release.**

jobs:
  Release:
    uses: ./.github/workflows/publish.yaml
    with:
      git_ref: ${{ github.ref }}
      channel: custom
    secrets: inherit
